### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mykinator** [bwbaugh/wikipedia-extractor#10]
> python WikiExtractor.py 
>   File "WikiExtractor.py", line 877
>     afterPat = { o:re.compile(openPat+'|'+c, re.DOTALL) for o,c in izip(openDelim, closeDelim)}
>                                                           ^
> SyntaxError: invalid syntax
# 

Any idea what I am doing wrong here? I am using python 2.6.1

**Comment by bwbaugh** [comment]
Looks like they're using a dictionary comprehension, which is only available in Python 2.7+. If that's the only Python 2.6 incompatible line, you could replace it with:

``` python
afterPat = dict(
    (o, re.compile(openPat+'|'+c, re.DOTALL))
    for o,c in izip(openDelim, closeDelim)
)
```
