### ISSUE TITLE
link to the developers github repo

### ISSUE THREAD

**Issue by Munzey** [bwbaugh/wikipedia-extractor#14]
Hi,
I see you've had this repo up prior to attardi's (kudos to you!) but I think it would be clearer now if you added a link to the [developers github repo](https://github.com/attardi/wikiextractor) in your description considering its a project still in development.
cheers
Tristan

**Comment by bwbaugh** [comment]
I've added that as a link in this repo's description. I'd like to keep the original URL as well (to the medialab page) since it has other information as well.

Hopefully that is satisfactory? The developer might want to link to their repo from the medialab page as well. :-)

**Comment by Munzey** [comment]
ye nice! My main reasoning is that you have open issues (such as #6) that have actually now been solved on the developer's page, also that your page comes up as the first couple of hits on google. But yes i agree that should probably be the case on the medialab page too!
