### ISSUE TITLE
Anchor is undefined

### ISSUE THREAD

**Issue by jmhessel** [bwbaugh/wikipedia-extractor#16]
On line 1764:

return '<a href="%s">%s</a>' % (urllib.quote(title.encode('utf-8')), anchor)

should 'anchor' be changed to 'label'?

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
