### ISSUE TITLE
Is it possible to keep the redirects?

### ISSUE THREAD

**Issue by hanito** [bwbaugh/wikipedia-extractor#17]
Hello Baugh.

I am using your source code to filter the wikipedia dump and it works really great. I just have a question concerning the redirect links. From what I understood, redirects are surrounded by [[ ]]. 
For example : [[Legal positivism]] where Legal Positivism is a redirect link.

The double brackets are filtered and removed in the final output. Which part of the python code should I modify in order to keep the redirects?

**Comment by hanito** [comment]
well it's easy sorry lolol I just need to comment # text = replaceInternalLinks(text) at line 1878

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
