### ISSUE TITLE
Error on English wikipedia dump

### ISSUE THREAD

**Issue by avostryakov** [bwbaugh/wikipedia-extractor#18]
After two days of work on an English Wikipedia dump (enwiki-20150602-pages-articles.xml) I got following stack trace:

  File "wiki_extractor.py", line 677, in expandTemplate
    instantiated = template.subst(params, self)
  File "wiki_extractor.py", line 301, in subst
    return ''.join([tpl.subst(params, extractor, depth) for tpl in self])
  File "wiki_extractor.py", line 358, in subst
    res =  extractor.expandTemplates(defaultValue)
  File "wiki_extractor.py", line 458, in expandTemplates
    res += wikitext[cur:s] + self.expandTemplate(wikitext[s+2:e-2])
  File "wiki_extractor.py", line 677, in expandTemplate
    instantiated = template.subst(params, self)
  File "wiki_extractor.py", line 301, in subst
    return ''.join([tpl.subst(params, extractor, depth) for tpl in self])
  File "wiki_extractor.py", line 351, in subst
    paramName = self.name.subst(params, extractor, depth+1)
  File "wiki_extractor.py", line 294, in subst
    logging.debug('subst tpl (%d, %d) %s', len(extractor.frame), depth, self)
  File "/usr/lib/python2.7/logging/**init**.py", line 1622, in debug
    root.debug(msg, _args, *_kwargs)
  File "/usr/lib/python2.7/logging/**init**.py", line 1139, in debug
    if self.isEnabledFor(DEBUG):
  File "/usr/lib/python2.7/logging/**init**.py", line 1351, in isEnabledFor
    return level >= self.getEffectiveLevel()
RuntimeError: maximum recursion depth exceeded

and the script stops to work.

**Comment by hanito** [comment]
what command did you use to run the code?

command:
python wikipedia-extractor/WikiExtractor.py -b 1000M -o extracted enwiki-20141106-pages-articles-multistream.xml 

This command will separate extracted enwiki-20141106-pages-articles-multistream.xml into files of 1000 M each and will place them in folder extracted.

**Comment by avostryakov** [comment]
I used following command:
python wikipedia-extractor/WikiExtractor.py -o extracted enwiki-20150602-pages-articles.xml

How I said for two days the script could extracted 2,6M articles and failed. How I read English Wikipedia has more than 4 M articles.

**Comment by avostryakov** [comment]
Do you need additional information and can you fix it?

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
