### ISSUE TITLE
Readme not works!

### ISSUE THREAD

**Issue by ChameleonRed** [bwbaugh/wikipedia-extractor#21]
Example of call from read me is invalid:

bzip2 -c -d "plwiki-latest-pages-articles.xml.bz2" | WikiExtractor.py -o -

Give unclear information instead parsing.

What does it mean?

$bzip2 -c -d "C:\Users\Crezary Wagner\Documents\GitHub\word2vec\plwiki-latest-pages-articles.xml.bz2"   | WikiExtractor.
py -o - -
Traceback (most recent call last):
  File "C:\Users\Crezary Wagner\Documents\GitHub\wikipedia-extractor\WikiExtractor.py", line 2587, in <module>
    main()
  File "C:\Users\Crezary Wagner\Documents\GitHub\wikipedia-extractor\WikiExtractor.py", line 2583, in main
    args.compress, args.processes)
  File "C:\Users\Crezary Wagner\Documents\GitHub\wikipedia-extractor\WikiExtractor.py", line 2297, in process_dump
    raise ValueError("to use templates with stdin dump, must supply explicit template-file")
ValueError: to use templates with stdin dump, must supply explicit template-file

bzip2: I/O or other error, bailing out.  Possible reason follows.
bzip2: No error
        Input file = C:\Users\Crezary Wagner\Documents\GitHub\word2vec\plwiki-latest-pages-articles.xml.bz2, output file
 = (stdout)

What templates???

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
