### ISSUE TITLE
 WikiExtractor.py - --no-templates > data.txt lead to errors.

### ISSUE THREAD

**Issue by ChameleonRed** [bwbaugh/wikipedia-extractor#22]
bzip2 -c -d "C:\Users\Crezary Wagner\Documents\GitHub

\word2vec\plwiki-latest-pages-articles.xml.bz2" | 

WikiExtractor.py - --no-templates > data.txt

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
