### ISSUE TITLE
OSError 12: cannot allocate memory

### ISSUE THREAD

**Issue by selaphy** [bwbaugh/wikipedia-extractor#24]
When I use wikipedia-extractor to process the newest enwiki (about 11.7GB) in ubuntu 14.04 with 2GB memory and 700G disk. I got the error when it processed in about 17 million articles.

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
