### ISSUE TITLE
Running on Portuguese Wiki in Windows.

### ISSUE THREAD

**Issue by vabatista** [bwbaugh/wikipedia-extractor#26]
I'm trying to run WikiExtractor for this wiki file (https://dumps.wikimedia.org/ptwiki/20160305/ptwiki-20160305-pages-meta-current.xml.bz2) using windows.

When I run this command:
c:> python WikiExtractor.py -cb 5M -o extracted ptwiki-20160305-pages-meta-current.xml.bz2

All wiki-pages return this error:
![wikiextractor](https://cloud.githubusercontent.com/assets/1828654/14322802/8288746c-fbf4-11e5-9894-6622e89e941e.png)

**Comment by Dither** [comment]
The current script seems broken in some places:

1) Missing  `escape_doc` global for some reason;
2) `keepLists` is undefined (wrong `L` case);
```python
class Extractor(object):
    """
    An extraction task on a article.
    """
    ##
    # Whether to preserve links in output
    keepLinks = False

    ##
    # Whether to preserve section titles
    keepSections = True

    ##
    # Whether to preserve lists
    keepLists = False

    ##
    # Whether to output HTML instead of text
    toHTML = False

    ##
    # Whether to expand templates
    expand_templates = True

    ##
    # Whether to escape doc
    escape_doc = False

# ...

        if Extractor.escape_doc:
            text = cgi.escape(text)
```

**ps:** Also it seems as a nice idea to exit extraction of redirect-type pages:
```python
        logging.debug("%s\t%s", self.id, self.title)
        text = self.clean()
        if len(text) < 2 or text.find('#REDIRECT') != -1:
            return
```
Plus optionally disable `<doc>` tag generation. (I just commented them out.)

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor

---

For what it's worth, it looks like the official repo has a newer version of the script than the [wiki website](http://medialab.di.unipi.it/wiki/Wikipedia_Extractor) that this repo is mirroring.
