### ISSUE TITLE
title with colon won't be extracted

### ISSUE THREAD

**Issue by benck** [bwbaugh/wikipedia-extractor#4]
I don't really know why do these lines of code mean:
            if (colon < 0 or title[:colon] in acceptedNamespaces) and \
                    not redirect:

Because if there is a wiki page with title like "Battle: Los Angeles", this page will be ignored since it's not in the acceptedNamespaces. Is this reasonable?

http://en.wikipedia.org/wiki/Battle:_Los_Angeles

**Comment by hanito** [comment]
Did you modify this line of code? any update?

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
