### ISSUE TITLE
WikiExtractor crash consistently during extraction in folder JK with no error on output or log

### ISSUE THREAD

**Issue by linearregression** [bwbaugh/wikipedia-extractor#5]
source file:
http://dumps.wikimedia.org/enwiki/20140502/enwiki-20140502-pages-articles-multistream.xml.bz2

command:
setsid nohup cat wiki.xml | ./WikiExtractor.py -c -l -o extracted > /dev/null 2>&1 &

Expect in folder extracted will list subfolders from AA to ZZ.
But always stop till JK
- size when stopped was 3.5G.
- enwiki-20140502-pages-articles-multistream.xml.bz2 is more than 10G

It is unsure why it stops

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
