### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by yinhangbupt** [bwbaugh/wikipedia-extractor#8]
I run the python program by the command (in linux):
bzcat zhwiki-latest-pages-articles.xml.bz2 | python WikiExtractor.py -cb 250k -o extracted

And I get:
usage: WikiExtractor.py [-h] [-o OUTPUT] [-b n[KM]] [-B BASE] [-c] [-l]
                        [-ns ns1,ns2] [-q] [-s] [-a] [--templates TEMPLATES]
                        [-v]
                        input
WikiExtractor.py: error: too few arguments

**Comment by hellowali** [comment]
I got the same problem. Then I tried the following command,it works.
python WikiExtractor.py -b 1000M -o extracted zhwiki-latest-pages-articles.xml.bz2

**Comment by iamnewtogithub** [comment]
Hi,

I get:
$ python WikiExtractor.py -b 1000M -o extracted enwiki-20141106-pages-articles-multistream.xml.bz2
INFO: Preprocessing dump to collect template definitions: this may take some time.
INFO: Starting processing pages from enwiki-20141106-pages-articles-multistream.xml.bz2.
INFO: Using 2 CPUs.

But

**Comment by iamnewtogithub** [comment]
Sorry, but I just get zero length o/p:

./extracted:
total 12
drwxrwxr-x. 3 awp awp 4096 Jul  1 22:30 .
drwxrwxr-x. 4 awp awp 4096 Jul  1 22:30 ..
drwxrwxr-x. 2 awp awp 4096 Jul  1 22:30 AA

./extracted/AA:
total 8
drwxrwxr-x. 2 awp awp 4096 Jul  1 22:30 .
drwxrwxr-x. 3 awp awp 4096 Jul  1 22:30 ..
-rw-rw-r--. 1 awp awp    0 Jul  1 22:30 wiki_00

**Comment by jonaprieto** [comment]
It's a shame that the current version doesn't work. I was looking in the last commits and the most recent version that works for me using the syntax we saw in the examples is the following:

https://github.com/bwbaugh/wikipedia-extractor/blob/97f354240a1c91cce369598eed50e60774897668/WikiExtractor.py

It works: 

``` bash
bzcat zhwiki-latest-pages-articles.xml.bz2 | python WikiExtractor.py -cb 250k -o extracted
```

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
